# Generated by Django 3.1.3 on 2021-03-25 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.TextField()),
                ('surname', models.TextField()),
                ('unique_id', models.TextField()),
                ('q1_sub', models.BooleanField(default=False)),
                ('q2_sub', models.BooleanField(default=False)),
                ('init_time', models.DateTimeField(default=None, null=True)),
                ('q1_start', models.DateTimeField(blank=True, default=None, null=True)),
                ('q2_start', models.DateTimeField(blank=True, default=None, null=True)),
                ('q1_exp', models.DateTimeField(blank=True, default=None, null=True)),
                ('q2_exp', models.DateTimeField(blank=True, default=None, null=True)),
                ('q1_end', models.DateTimeField(blank=True, default=None, null=True)),
                ('q2_end', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('language', models.TextField()),
                ('template', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('q_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('time', models.IntegerField(null=True)),
                ('templates', models.ManyToManyField(to='avaloq_app.CodeTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reviewer', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Code_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final', models.BooleanField(default=False)),
                ('code', models.TextField(null=True)),
                ('language', models.TextField(null=True)),
                ('verdicts', models.TextField(null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaloq_app.candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaloq_app.question')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='questions',
            field=models.ManyToManyField(to='avaloq_app.Question'),
        ),
    ]
